version = "v0.0.1"
host = ""
port = "8087"
token_secret = "437b059d-bd8b-40d5-920a-341bb8a3f15f"
database_user_name = "root"
database_user_password = ""
database_name = "duval"
database_host = "localhost"
database_port = "3306"