package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"duval/internal/graph"
	"duval/internal/graph/model"
	"fmt"
)

// ID is the resolver for the id field.
func (r *passwordResolver) ID(ctx context.Context, obj *model.Password) (int, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *passwordResolver) UserID(ctx context.Context, obj *model.Password) (int, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// Password returns graph.PasswordResolver implementation.
func (r *Resolver) Password() graph.PasswordResolver { return &passwordResolver{r} }

type passwordResolver struct{ *Resolver }
