// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Address struct {
	Id          int        `json:"Id"`
	CreatedAt   time.Time  `json:"CreatedAt"`
	UpdatedAt   time.Time  `json:"UpdatedAt"`
	DeletedAt   *time.Time `json:"DeletedAt,omitempty"`
	Country     string     `json:"Country"`
	City        string     `json:"City"`
	Latitude    float64    `json:"Latitude"`
	Longitude   float64    `json:"Longitude"`
	Street      string     `json:"Street"`
	FullAddress string     `json:"FullAddress"`
	Xid         string     `json:"Xid"`
}

type AddressInput struct {
	Country     *string  `json:"country"`
	City        *string  `json:"city"`
	Latitude    *float64 `json:"latitude"`
	Longitude   *float64 `json:"longitude"`
	Street      *string  `json:"street"`
	FullAddress *string  `json:"full_address"`
}

type Asset struct {
	Id          int        `json:"Id"`
	CreatedAt   time.Time  `json:"CreatedAt"`
	UpdatedAt   time.Time  `json:"UpdatedAt"`
	DeletedAt   *time.Time `json:"DeletedAt,omitempty"`
	Description string     `json:"Description"`
}

type AssetInput struct {
	Description *string `json:"description"`
}

type Authorization struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	UserId    int        `json:"UserId"`
	Level     int        `json:"Level"`
}

type CalendarPlanning struct {
	Id              int        `json:"Id"`
	CreatedAt       time.Time  `json:"CreatedAt"`
	UpdatedAt       time.Time  `json:"UpdatedAt"`
	DeletedAt       *time.Time `json:"DeletedAt,omitempty"`
	AuthorizationId int        `json:"AuthorizationId"`
	StartDateTime   time.Time  `json:"StartDateTime"`
	EndDateTime     time.Time  `json:"EndDateTime"`
	Description     string     `json:"Description"`
}

type CalendarPlanningActor struct {
	Id                 int        `json:"Id"`
	CreatedAt          time.Time  `json:"CreatedAt"`
	UpdatedAt          time.Time  `json:"UpdatedAt"`
	DeletedAt          *time.Time `json:"DeletedAt,omitempty"`
	AuthorizationId    int        `json:"AuthorizationId"`
	CalendarPlanningId int        `json:"CalendarPlanningId"`
}

type CalendarPlanningInput struct {
	StartDateTime *time.Time `json:"start_date_time"`
	EndDateTime   *time.Time `json:"end_date_time"`
	Description   *string    `json:"description"`
}

type Code struct {
	Id               int        `json:"Id"`
	CreatedAt        time.Time  `json:"CreatedAt"`
	UpdatedAt        time.Time  `json:"UpdatedAt"`
	DeletedAt        *time.Time `json:"DeletedAt,omitempty"`
	UserId           int        `json:"UserId"`
	VerificationCode int        `json:"VerificationCode"`
}

type Contract struct {
	Id            int        `json:"Id"`
	CreatedAt     time.Time  `json:"CreatedAt"`
	UpdatedAt     time.Time  `json:"UpdatedAt"`
	DeletedAt     *time.Time `json:"DeletedAt,omitempty"`
	TutorId       int        `json:"TutorId"`
	ParentId      int        `json:"ParentId"`
	StudentId     int        `json:"StudentId"`
	StartDate     time.Time  `json:"StartDate"`
	EndDate       time.Time  `json:"EndDate"`
	PaymentType   int        `json:"PaymentType"`
	SalaryValue   float64    `json:"SalaryValue"`
	PaymentMethod int        `json:"PaymentMethod"`
}

type ContractInput struct {
	TutorId       *int       `json:"tutor_id"`
	ParentId      *int       `json:"parent_id"`
	StudentId     *int       `json:"student_id"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	PaymentType   *int       `json:"payment_type"`
	SalaryValue   *float64   `json:"salary_value"`
	PaymentMethod *int       `json:"payment_method"`
}

type ContractTimesheetDetail struct {
	Id         int        `json:"Id"`
	CreatedAt  time.Time  `json:"CreatedAt"`
	UpdatedAt  time.Time  `json:"UpdatedAt"`
	DeletedAt  *time.Time `json:"DeletedAt,omitempty"`
	ContractId int        `json:"ContractId"`
	Date       time.Time  `json:"Date"`
	Hours      float64    `json:"Hours"`
}

type ContractTimesheetDetailInput struct {
	ContractId *int       `json:"contract_id"`
	Date       *time.Time `json:"date"`
	Hours      *float64   `json:"hours"`
}

type Education struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	Name      string     `json:"Name"`
}

type Mark struct {
	Id            int        `json:"Id"`
	CreatedAt     time.Time  `json:"CreatedAt"`
	UpdatedAt     time.Time  `json:"UpdatedAt"`
	DeletedAt     *time.Time `json:"DeletedAt,omitempty"`
	UserId        int        `json:"UserId"`
	AuthorId      int        `json:"AuthorId"`
	AuthorComment string     `json:"AuthorComment"`
	AuthorMark    int        `json:"AuthorMark"`
}

type MarkInput struct {
	UserId        *int    `json:"user_id"`
	AuthorId      *int    `json:"author_id"`
	AuthorComment *string `json:"author_comment"`
	AuthorMark    *int    `json:"author_mark"`
}

type Media struct {
	Id          int        `json:"Id"`
	CreatedAt   time.Time  `json:"CreatedAt"`
	UpdatedAt   time.Time  `json:"UpdatedAt"`
	DeletedAt   *time.Time `json:"DeletedAt,omitempty"`
	FileName    string     `json:"FileName"`
	Extension   string     `json:"Extension"`
	Xid         string     `json:"Xid"`
	ContentType int        `json:"ContentType"`
}

type MediaThumb struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	Extension string     `json:"Extension"`
	MediaXid  string     `json:"MediaXid"`
	Xid       string     `json:"Xid"`
}

type Message struct {
	Id               int        `json:"Id"`
	CreatedAt        time.Time  `json:"CreatedAt"`
	UpdatedAt        time.Time  `json:"UpdatedAt"`
	DeletedAt        *time.Time `json:"DeletedAt,omitempty"`
	ResourceType     int        `json:"ResourceType"`
	ResourceNumber   int        `json:"ResourceNumber"`
	ResourceValue    int        `json:"ResourceValue"`
	ResourceLabel    string     `json:"ResourceLabel"`
	ResourceLanguage int        `json:"ResourceLanguage"`
}

type MessageInput struct {
	ResourceType     *int    `json:"resource_type"`
	ResourceValue    *int    `json:"resource_value"`
	ResourceNumber   *int    `json:"resource_number"`
	ResourceLabel    *string `json:"resource_label"`
	ResourceLanguage *int    `json:"resource_language"`
}

type Mutation struct {
}

type Password struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	UserId    int        `json:"UserId"`
	Hash      string     `json:"Hash"`
}

type PasswordInput struct {
	Hash *string `json:"hash"`
}

type PhoneNumber struct {
	Id                int        `json:"Id"`
	CreatedAt         time.Time  `json:"CreatedAt"`
	UpdatedAt         time.Time  `json:"UpdatedAt"`
	DeletedAt         *time.Time `json:"DeletedAt,omitempty"`
	MobilePhoneNumber string     `json:"MobilePhoneNumber"`
	IsUrgency         bool       `json:"IsUrgency"`
}

type PhoneNumberInput struct {
	MobilePhoneNumber *string `json:"mobile_phone_number"`
	IsUrgency         *bool   `json:"is_urgency"`
}

type Post struct {
	Id             int        `json:"Id"`
	CreatedAt      time.Time  `json:"CreatedAt"`
	UpdatedAt      time.Time  `json:"UpdatedAt"`
	DeletedAt      *time.Time `json:"DeletedAt,omitempty"`
	PublisherId    int        `json:"PublisherId"`
	Content        string     `json:"Content"`
	ExpirationDate time.Time  `json:"ExpirationDate"`
}

type PostInput struct {
	PublisherId    *int       `json:"publisher_id"`
	Content        *string    `json:"content"`
	ExpirationDate *time.Time `json:"expiration_date"`
}

type PostTag struct {
	Id         int        `json:"Id"`
	CreatedAt  time.Time  `json:"CreatedAt"`
	UpdatedAt  time.Time  `json:"UpdatedAt"`
	DeletedAt  *time.Time `json:"DeletedAt,omitempty"`
	PostId     int        `json:"PostId"`
	TagContent string     `json:"TagContent"`
}

type PostTagInput struct {
	PostId     *int    `json:"post_id"`
	TagContent *string `json:"tag_content"`
}

type PostView struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	PostId    int        `json:"PostId"`
	ViewerId  int        `json:"ViewerId"`
}

type QRCodeRegistry struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	UserId    int        `json:"UserId"`
	Xid       string     `json:"Xid"`
	IsUsed    bool       `json:"IsUsed"`
}

type Query struct {
}

type School struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	Name      string     `json:"Name"`
}

type SchoolInput struct {
	Name *string `json:"name"`
}

type SchoolSubject struct {
	Id           int        `json:"Id"`
	CreatedAt    time.Time  `json:"CreatedAt"`
	UpdatedAt    time.Time  `json:"UpdatedAt"`
	DeletedAt    *time.Time `json:"DeletedAt,omitempty"`
	SchoolNumber int        `json:"SchoolNumber"`
	Name         string     `json:"Name"`
}

type SchoolSubjectInput struct {
	SchoolNumber *int    `json:"school_number"`
	Name         *string `json:"name"`
}

type Subject struct {
	Id               int        `json:"Id"`
	CreatedAt        time.Time  `json:"CreatedAt"`
	UpdatedAt        time.Time  `json:"UpdatedAt"`
	DeletedAt        *time.Time `json:"DeletedAt,omitempty"`
	EducationLevelId int        `json:"EducationLevelId"`
	Name             string     `json:"Name"`
}

type SubjectInput struct {
	EducationLevelId *int    `json:"education_level_id"`
	Name             *string `json:"name"`
}

type User struct {
	Id                    int        `json:"Id"`
	CreatedAt             time.Time  `json:"CreatedAt"`
	UpdatedAt             time.Time  `json:"UpdatedAt"`
	DeletedAt             *time.Time `json:"DeletedAt,omitempty"`
	Name                  string     `json:"Name"`
	FamilyName            string     `json:"FamilyName"`
	NickName              string     `json:"NickName"`
	Email                 string     `json:"Email"`
	Matricule             string     `json:"Matricule"`
	Age                   int        `json:"Age"`
	BirthDate             time.Time  `json:"BirthDate"`
	Sex                   int        `json:"Sex"`
	Lang                  int        `json:"Lang"`
	Status                int        `json:"Status"`
	ProfileImageXid       string     `json:"ProfileImageXid"`
	Description           string     `json:"Description"`
	CoverText             string     `json:"CoverText"`
	Profile               string     `json:"Profile"`
	ExperienceDetail      string     `json:"ExperienceDetail"`
	AdditionalDescription string     `json:"AdditionalDescription"`
	AddOnTitle            string     `json:"AddOnTitle"`
}

type UserAddress struct {
	Id          int        `json:"Id"`
	CreatedAt   time.Time  `json:"CreatedAt"`
	UpdatedAt   time.Time  `json:"UpdatedAt"`
	DeletedAt   *time.Time `json:"DeletedAt,omitempty"`
	UserId      int        `json:"UserId"`
	AddressId   int        `json:"AddressId"`
	AddressType string     `json:"AddressType"`
}

type UserAuthorizationLink struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	LinkType  int        `json:"LinkType"`
}

type UserAuthorizationLinkActor struct {
	Id                      int        `json:"Id"`
	CreatedAt               time.Time  `json:"CreatedAt"`
	UpdatedAt               time.Time  `json:"UpdatedAt"`
	DeletedAt               *time.Time `json:"DeletedAt,omitempty"`
	UserAuthorizationLinkId int        `json:"UserAuthorizationLinkId"`
	AuthorizationId         int        `json:"AuthorizationId"`
}

type UserEducationLevelSubject struct {
	Id        int        `json:"Id"`
	CreatedAt time.Time  `json:"CreatedAt"`
	UpdatedAt time.Time  `json:"UpdatedAt"`
	DeletedAt *time.Time `json:"DeletedAt,omitempty"`
	UserId    int        `json:"UserId"`
	SubjectId int        `json:"SubjectId"`
}

type UserInput struct {
	Name       *string    `json:"name"`
	FamilyName *string    `json:"family_name"`
	NickName   *string    `json:"nick_name"`
	Email      *string    `json:"email"`
	BirthDate  *time.Time `json:"birth_date"`
	Sex        *int       `json:"sex"`
	Lang       *int       `json:"lang"`
}

type UserMediaDetail struct {
	Id           int        `json:"Id"`
	CreatedAt    time.Time  `json:"CreatedAt"`
	UpdatedAt    time.Time  `json:"UpdatedAt"`
	DeletedAt    *time.Time `json:"DeletedAt,omitempty"`
	OwnerId      int        `json:"OwnerId"`
	DocumentType int        `json:"DocumentType"`
	DocumentXid  string     `json:"DocumentXid"`
}

type UserPhoneNumber struct {
	Id            int        `json:"Id"`
	CreatedAt     time.Time  `json:"CreatedAt"`
	UpdatedAt     time.Time  `json:"UpdatedAt"`
	DeletedAt     *time.Time `json:"DeletedAt,omitempty"`
	UserId        int        `json:"UserId"`
	PhoneNumberId int        `json:"PhoneNumberId"`
}
