// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Address struct {
	Id          int        `json:"id"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
	Country     string     `json:"country"`
	City        string     `json:"city"`
	Latitude    float64    `json:"latitude"`
	Longitude   float64    `json:"longitude"`
	Street      string     `json:"street"`
	FullAddress string     `json:"fullAddress"`
	Xid         string     `json:"xid"`
}

type AddressInput struct {
	Country     *string  `json:"country"`
	City        *string  `json:"city"`
	Latitude    *float64 `json:"latitude"`
	Longitude   *float64 `json:"longitude"`
	Street      *string  `json:"street"`
	FullAddress *string  `json:"fullAddress"`
}

type Asset struct {
	Id          int        `json:"id"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
	Description string     `json:"description"`
}

type AssetInput struct {
	Description *string `json:"description"`
}

type Authorization struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	UserId    int        `json:"userId"`
	Level     int        `json:"level"`
}

type CalendarPlanning struct {
	Id              int        `json:"id"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	DeletedAt       *time.Time `json:"deletedAt"`
	AuthorizationId int        `json:"authorizationId"`
	StartDateTime   time.Time  `json:"startDateTime"`
	EndDateTime     time.Time  `json:"endDateTime"`
	Description     string     `json:"description"`
}

type CalendarPlanningActor struct {
	Id                 int        `json:"id"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	AuthorizationId    int        `json:"authorizationId"`
	CalendarPlanningId int        `json:"calendarPlanningId"`
}

type CalendarPlanningInput struct {
	StartDateTime *time.Time `json:"startDateTime"`
	EndDateTime   *time.Time `json:"endDateTime"`
	Description   *string    `json:"description"`
}

type Code struct {
	Id               int        `json:"id"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdatedAt        time.Time  `json:"updatedAt"`
	DeletedAt        *time.Time `json:"deletedAt"`
	UserId           int        `json:"userId"`
	VerificationCode int        `json:"verificationCode"`
}

type Contract struct {
	Id            int        `json:"id"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	DeletedAt     *time.Time `json:"deletedAt"`
	TutorId       int        `json:"tutorId"`
	ParentId      int        `json:"parentId"`
	StudentId     int        `json:"studentId"`
	StartDate     time.Time  `json:"startDate"`
	EndDate       time.Time  `json:"endDate"`
	PaymentType   int        `json:"paymentType"`
	SalaryValue   float64    `json:"salaryValue"`
	PaymentMethod int        `json:"paymentMethod"`
}

type ContractInput struct {
	TutorId       *int       `json:"tutorId"`
	ParentId      *int       `json:"parentId"`
	StudentId     *int       `json:"studentId"`
	StartDate     *time.Time `json:"startDate"`
	EndDate       *time.Time `json:"endDate"`
	PaymentType   *int       `json:"paymentType"`
	SalaryValue   *float64   `json:"salaryValue"`
	PaymentMethod *int       `json:"paymentMethod"`
}

type ContractTimesheetDetail struct {
	Id         int        `json:"id"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	DeletedAt  *time.Time `json:"deletedAt"`
	ContractId int        `json:"contractId"`
	Date       time.Time  `json:"date"`
	Hours      float64    `json:"hours"`
}

type ContractTimesheetDetailInput struct {
	ContractId *int       `json:"contractId"`
	Date       *time.Time `json:"date"`
	Hours      *float64   `json:"hours"`
}

type Education struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	Name      string     `json:"name"`
}

type Mark struct {
	Id            int        `json:"id"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	DeletedAt     *time.Time `json:"deletedAt"`
	UserId        int        `json:"userId"`
	AuthorId      int        `json:"authorId"`
	AuthorComment string     `json:"authorComment"`
	AuthorMark    int        `json:"authorMark"`
}

type MarkInput struct {
	UserId        *int    `json:"userId"`
	AuthorId      *int    `json:"authorId"`
	AuthorComment *string `json:"authorComment"`
	AuthorMark    *int    `json:"authorMark"`
}

type Media struct {
	Id          int        `json:"id"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
	FileName    string     `json:"fileName"`
	Extension   string     `json:"extension"`
	Xid         string     `json:"xid"`
	ContentType int        `json:"contentType"`
}

type MediaThumb struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	Extension string     `json:"extension"`
	MediaXid  string     `json:"mediaXid"`
	Xid       string     `json:"xid"`
}

type Message struct {
	Id               int        `json:"id"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdatedAt        time.Time  `json:"updatedAt"`
	DeletedAt        *time.Time `json:"deletedAt"`
	ResourceType     int        `json:"resourceType"`
	ResourceNumber   int        `json:"resourceNumber"`
	ResourceValue    int        `json:"resourceValue"`
	ResourceLabel    string     `json:"resourceLabel"`
	ResourceLanguage int        `json:"resourceLanguage"`
}

type MessageInput struct {
	ResourceType     *int    `json:"resourceType"`
	ResourceValue    *int    `json:"resourceValue"`
	ResourceNumber   *int    `json:"resourceNumber"`
	ResourceLabel    *string `json:"resourceLabel"`
	ResourceLanguage *int    `json:"resourceLanguage"`
}

type Mutation struct {
}

type Password struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	UserId    int        `json:"userId"`
	Hash      string     `json:"hash"`
}

type PasswordInput struct {
	Hash *string `json:"hash"`
}

type PhoneNumber struct {
	Id                int        `json:"id"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
	DeletedAt         *time.Time `json:"deletedAt"`
	MobilePhoneNumber string     `json:"mobilePhoneNumber"`
	IsUrgency         bool       `json:"isUrgency"`
}

type PhoneNumberInput struct {
	MobilePhoneNumber *string `json:"mobilePhoneNumber"`
	IsUrgency         *bool   `json:"isUrgency"`
}

type Post struct {
	Id             int        `json:"id"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	DeletedAt      *time.Time `json:"deletedAt"`
	PublisherId    int        `json:"publisherId"`
	Content        string     `json:"content"`
	ExpirationDate time.Time  `json:"expirationDate"`
}

type PostInput struct {
	PublisherId    *int       `json:"publisherId"`
	Content        *string    `json:"content"`
	ExpirationDate *time.Time `json:"expirationDate"`
}

type PostTag struct {
	Id         int        `json:"id"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	DeletedAt  *time.Time `json:"deletedAt"`
	PostId     int        `json:"postId"`
	TagContent string     `json:"tagContent"`
}

type PostTagInput struct {
	PostId     *int    `json:"postId"`
	TagContent *string `json:"tagContent"`
}

type PostView struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	PostId    int        `json:"postId"`
	ViewerId  int        `json:"viewerId"`
}

type QRCodeRegistry struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	UserId    int        `json:"userId"`
	Xid       string     `json:"xid"`
	IsUsed    bool       `json:"isUsed"`
}

type Query struct {
}

type Subject struct {
	Id               int        `json:"id"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdatedAt        time.Time  `json:"updatedAt"`
	DeletedAt        *time.Time `json:"deletedAt"`
	EducationLevelId int        `json:"educationLevelId"`
	Name             string     `json:"name"`
}

type SubjectInput struct {
	EducationLevelId *int    `json:"educationLevelId"`
	Name             *string `json:"name"`
}

type User struct {
	Id                    int        `json:"id"`
	CreatedAt             time.Time  `json:"createdAt"`
	UpdatedAt             time.Time  `json:"updatedAt"`
	DeletedAt             *time.Time `json:"deletedAt"`
	Name                  string     `json:"name"`
	FamilyName            string     `json:"familyName"`
	NickName              string     `json:"nickName"`
	Email                 string     `json:"email"`
	Matricule             string     `json:"matricule"`
	Age                   int        `json:"age"`
	BirthDate             time.Time  `json:"birthDate"`
	Sex                   int        `json:"sex"`
	Lang                  int        `json:"lang"`
	Status                int        `json:"status"`
	ProfileImageXid       string     `json:"profileImageXid"`
	Description           string     `json:"description"`
	CoverText             string     `json:"coverText"`
	Profile               string     `json:"profile"`
	ExperienceDetail      string     `json:"experienceDetail"`
	AdditionalDescription string     `json:"additionalDescription"`
	AddOnTitle            string     `json:"addOnTitle"`
}

type UserAddress struct {
	Id          int        `json:"id"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
	UserId      int        `json:"userId"`
	AddressId   int        `json:"addressId"`
	AddressType string     `json:"addressType"`
}

type UserAuthorizationLink struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	LinkType  int        `json:"linkType"`
}

type UserAuthorizationLinkActor struct {
	Id                      int        `json:"id"`
	CreatedAt               time.Time  `json:"createdAt"`
	UpdatedAt               time.Time  `json:"updatedAt"`
	DeletedAt               *time.Time `json:"deletedAt"`
	UserAuthorizationLinkId int        `json:"userAuthorizationLinkId"`
	AuthorizationId         int        `json:"authorizationId"`
}

type UserCoursePreference struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	UserId    int        `json:"userId"`
	IsOnline  bool       `json:"isOnline"`
}

type UserEducationLevelSubject struct {
	Id        int        `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	UserId    int        `json:"userId"`
	SubjectId int        `json:"subjectId"`
}

type UserInput struct {
	Name                  *string    `json:"name"`
	FamilyName            *string    `json:"familyName"`
	NickName              *string    `json:"nickName"`
	Email                 *string    `json:"email"`
	BirthDate             *time.Time `json:"birthDate"`
	Sex                   *int       `json:"sex"`
	Lang                  *int       `json:"lang"`
	Description           *string    `json:"description"`
	CoverText             *string    `json:"coverText"`
	Profile               *string    `json:"profile"`
	ExperienceDetail      *string    `json:"experienceDetail"`
	AdditionalDescription *string    `json:"additionalDescription"`
	AddOnTitle            *string    `json:"addOnTitle"`
}

type UserMediaDetail struct {
	Id           int        `json:"id"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt"`
	OwnerId      int        `json:"ownerId"`
	DocumentType int        `json:"documentType"`
	DocumentXid  string     `json:"documentXid"`
}

type UserPhoneNumber struct {
	Id            int        `json:"id"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	DeletedAt     *time.Time `json:"deletedAt"`
	UserId        int        `json:"userId"`
	PhoneNumberId int        `json:"phoneNumberId"`
}
